### ISSUE TITLE
Error when trying to unpack C0000 DCX file sekiro

### ISSUE THREAD

**Issue by Kinkerguy5** [JKAnderson/Yabber#16]
Unhandled exception: System.IO.InvalidDataException: Read Int32: 0x1000018 | Expected Int32: 0x18
   at SoulsFormats.BinaryReaderEx.AssertValue[T](Func`1 readValue, String typeName, String valueFormat, T[] options)
   at SoulsFormats.BinaryReaderEx.AssertInt32(Int32[] options)
   at SoulsFormats.DCX.DecompressDCXDFLT(BinaryReaderEx br, Type type)
   at SoulsFormats.DCX.Decompress(String path, Type& type)
   at Yabber.Program.UnpackFile(String sourceFile)
   at Yabber.Program.Main(String[] args)

One or more errors were encountered and displayed above.
Press any key to exit.

Trying to merge 2 mods but whenever i try to unpack the C0000.anibnd.dcx file of the main mod i want to merge with i get this error, i put the oo2core_6_win64.dll file in the lib folder as required and i'm at a loss, any idea how i may be able to fix this? I'm using the most recent version of yabber

**Comment by Kinkerguy5** [comment]
Found something out about this issue, it seems like it only gives this error with the specific mod that i was trying to modify, when i tried a different mod it worked without problems, still no clue why the error occurs on that specific mod or how to fix that
