### ISSUE TITLE
Error when unpacking Armored Core DCX

### ISSUE THREAD

**Issue by ghost** [JKAnderson/Yabber#17]
When trying to unpack AC6 DCX given this error. 

Decompressing DCX: bd_m_1010.partsbnd.dcx...
Unhandled exception: System.IO.InvalidDataException: Read Int32: 0x9000000 | Expected Int32: 0x6000000
   at SoulsFormats.BinaryReaderEx.AssertValue[T](Func`1 readValue, String typeName, String valueFormat, T[] options)
   at SoulsFormats.BinaryReaderEx.AssertInt32(Int32[] options)
   at SoulsFormats.DCX.DecompressDCXKRAK(BinaryReaderEx br)
   at SoulsFormats.DCX.Decompress(String path, Type& type)
   at Yabber.Program.Decompress(String sourceFile)
   at Yabber.Program.Main(String[] args)

**Comment by ividyon** [comment]
@ghost Use [WitchyBND](https://github.com/ividyon/WitchyBND).
