### ISSUE TITLE
Fails to repack certain files

### ISSUE THREAD

**Issue by therealcharmics** [JKAnderson/Yabber#8]
Hello,

Thank you for the software!

Was using Yabber to edit and repack some gparams. These are from Bloodborne. Simply extracting and repacking without editing way fails.

[gparams.zip](https://github.com/JKAnderson/Yabber/files/7955913/gparams.zip)

The error reads as follows:

```
Repacking GPARAM: m29_00_0100.gparam.dcx.xml...
Unhandled exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex
   at System.ParseNumbers.StringToInt(String s, Int32 radix, Int32 flags, Int32* currPos)
   at System.Convert.ToByte(String value, Int32 fromBase)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Yabber.YGPARAM.Repack(String sourceFile)
   at Yabber.Program.UnpackFile(String sourceFile)
   at Yabber.Program.Main(String[] args)

One or more errors were encountered and displayed above.
Press any key to exit.
```

Hopefully this can be fixed at some point?

Thank you for your time.

**Comment by RunDevelopment** [comment]
This has been fixed in commit 307a3ab9b1e6eacac55f6287fd5cb72a68f20663.

@JKAnderson Could you please make a new release to fix this issue?

@therealcharmics In the meantime, you can clone the repo and build Yabber yourself to get the fix.
